<?php

require_once dirname(__FILE__) . '/../ArabicToRoman.php';

/**
 * Test class for ArabicToRoman.
 * Generated by PHPUnit on 2011-12-16 at 14:48:13.
 */
class ArabicToRomanTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ArabicToRoman
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ArabicToRoman;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	public function testEins() {
		$this->assertEquals('I', $this->object->getArabicToRoman(1));
	}
	public function testZwei() {
		$this->assertEquals('II', $this->object->getArabicToRoman(2));
	}
	public function testDrei() {
		$this->assertEquals('III', $this->object->getArabicToRoman(3));
	}
	public function testVier() {
		$this->assertEquals('IV', $this->object->getArabicToRoman(4));
	}
	public function testFuenf() {
		$this->assertEquals('V', $this->object->getArabicToRoman(5));
	}
	public function test1999() {
		$this->assertEquals('MCMXCIX', $this->object->getArabicToRoman(1999));
	}
	public function test2011() {
		$this->assertEquals('MMXI', $this->object->getArabicToRoman(2011));
	}
}

?>
